# Example class configuration for auto_battlebot
# Specify which implementations to use for each interface

camera = "realsense"
field_model = "default"
field_filter = "default"
keypoint_model = "default"
robot_filter = "default"
navigation = "default"
transmitter = "default"
